"""create fields table

Revision ID: 1991532703dc
Revises: 46d144661ea0
Create Date: 2026-08-07 02:03:06.104202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1991532703dc'
down_revision = '46d144661ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('surface_type', sa.Unicode(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='INACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("field_type IN ('FIVE_A_SIDE', 'SEVEN_A_SIDE', 'ELEVEN_A_SIDE')", name='ck_fields_type'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_fields_status'),
    sa.CheckConstraint('capacity > 0', name='ck_fields_capacity_positive'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_fields_venue_name')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index('ix_fields_venue_status', ['venue_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index('ix_fields_venue_status')

    op.drop_table('fields')
    # ### end Alembic commands ###
