"""remove manual owner approval fields

Revision ID: 3dae30a3dfcb
Revises: 8aecda33c702
Create Date: 2026-08-08 02:14:09.239041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '3dae30a3dfcb'
down_revision = '8aecda33c702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status_owner_due'))
        batch_op.create_index('ix_bookings_status_initial_payment_due', ['status', 'initial_payment_due_at'], unique=False)
        batch_op.drop_column('owner_response_due_at')
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_response_due_at', mssql.DATETIME2(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_bookings_status_initial_payment_due')
        batch_op.create_index(batch_op.f('ix_bookings_status_owner_due'), ['status', 'owner_response_due_at'], unique=False)

    # ### end Alembic commands ###
