"""add payment foundation and contribution allocation

Revision ID: 3f1f38dab5f1
Revises: 3dae30a3dfcb
Create Date: 2026-08-08 03:05:56.907506

"""

from decimal import Decimal

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '3f1f38dab5f1'
down_revision = '3dae30a3dfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contribution_type', sa.String(length=30), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("((contribution_type IN ('CREATOR', 'TOP_UP') AND slot_number IS NULL) OR (contribution_type IN ('OPPONENT', 'PLAYER') AND slot_number IS NOT NULL AND slot_number > 0))", name='ck_booking_contributions_slot_number'),
    sa.CheckConstraint("contribution_type IN ('CREATOR', 'OPPONENT', 'PLAYER', 'TOP_UP')", name='ck_booking_contributions_type'),
    sa.CheckConstraint("status IN ('PENDING', 'PAID', 'EXPIRED', 'WAIVED', 'REFUND_PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FORFEITED')", name='ck_booking_contributions_status'),
    sa.CheckConstraint('amount_due >= 0', name='ck_booking_contributions_amount_due_non_negative'),
    sa.CheckConstraint('amount_paid >= 0 AND amount_paid <= amount_due', name='ck_booking_contributions_amount_paid_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_contributions', schema=None) as batch_op:
        batch_op.create_index('ix_booking_contributions_booking_status', ['booking_id', 'status'], unique=False)
        batch_op.create_index('uq_booking_contributions_external_slot', ['booking_id', 'contribution_type', 'slot_number'], unique=True, mssql_where=sa.text('slot_number IS NOT NULL'), sqlite_where=sa.text('slot_number IS NOT NULL'))

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('provider_trans_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_code', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("payment_method IN ('SIMULATED', 'MOMO_WALLET')", name='ck_payments_method'),
    sa.CheckConstraint("provider IN ('MOCK', 'MOMO')", name='ck_payments_provider'),
    sa.CheckConstraint("status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['booking_contributions.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_booking_created', ['booking_id', 'created_at'], unique=False)
        batch_op.create_index('uq_payments_provider_trans_id_not_null', ['provider_trans_id'], unique=True, mssql_where=sa.text('provider_trans_id IS NOT NULL'), sqlite_where=sa.text('provider_trans_id IS NOT NULL'))
        batch_op.create_index('uq_payments_success_contribution', ['contribution_id'], unique=True, mssql_where=sa.text("status = 'SUCCESS'"), sqlite_where=sa.text("status = 'SUCCESS'"))

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Unicode(length=500), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('provider_refund_trans_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_code', sa.String(length=20), nullable=True),
    sa.Column('refunded_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')", name='ck_refunds_status'),
    sa.CheckConstraint('amount > 0', name='ck_refunds_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('ix_refunds_booking_created', ['booking_id', 'created_at'], unique=False)
        batch_op.create_index('uq_refunds_provider_trans_id_not_null', ['provider_refund_trans_id'], unique=True, mssql_where=sa.text('provider_refund_trans_id IS NOT NULL'), sqlite_where=sa.text('provider_refund_trans_id IS NOT NULL'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_total_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('split_required_players', sa.Integer(), nullable=True))

    _backfill_booking_contributions()

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_bookings_split_player_configuration',
            "((payment_mode = 'SPLIT_PLAYERS' "
            "AND split_total_players IS NOT NULL "
            "AND split_required_players IS NOT NULL "
            "AND split_total_players > 1 "
            "AND split_required_players > 0 "
            "AND split_required_players < split_total_players) "
            "OR (payment_mode <> 'SPLIT_PLAYERS' "
            "AND split_total_players IS NULL "
            "AND split_required_players IS NULL))",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_bookings_split_player_configuration',
            type_='check',
        )
        batch_op.drop_column('split_required_players')
        batch_op.drop_column('split_total_players')

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index('uq_refunds_provider_trans_id_not_null', mssql_where=sa.text('provider_refund_trans_id IS NOT NULL'), sqlite_where=sa.text('provider_refund_trans_id IS NOT NULL'))
        batch_op.drop_index('ix_refunds_booking_created')

    op.drop_table('refunds')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('uq_payments_success_contribution', mssql_where=sa.text("status = 'SUCCESS'"), sqlite_where=sa.text("status = 'SUCCESS'"))
        batch_op.drop_index('uq_payments_provider_trans_id_not_null', mssql_where=sa.text('provider_trans_id IS NOT NULL'), sqlite_where=sa.text('provider_trans_id IS NOT NULL'))
        batch_op.drop_index('ix_payments_booking_created')

    op.drop_table('payments')
    with op.batch_alter_table('booking_contributions', schema=None) as batch_op:
        batch_op.drop_index('uq_booking_contributions_external_slot', mssql_where=sa.text('slot_number IS NOT NULL'), sqlite_where=sa.text('slot_number IS NOT NULL'))
        batch_op.drop_index('ix_booking_contributions_booking_status')

    op.drop_table('booking_contributions')
    # ### end Alembic commands ###


def _backfill_booking_contributions():
    """Create auditable allocations for bookings made before this revision."""
    bind = op.get_bind()
    bookings = sa.table(
        'bookings',
        sa.column('id', sa.Integer()),
        sa.column('user_id', sa.Integer()),
        sa.column('field_id', sa.Integer()),
        sa.column('payment_mode', sa.String()),
        sa.column('total_amount', sa.Numeric(12, 2)),
        sa.column('paid_amount', sa.Numeric(12, 2)),
        sa.column('status', sa.String()),
        sa.column('initial_payment_due_at', sa.DateTime()),
        sa.column('created_at', sa.DateTime()),
        sa.column('split_total_players', sa.Integer()),
        sa.column('split_required_players', sa.Integer()),
    )
    fields = sa.table(
        'fields',
        sa.column('id', sa.Integer()),
        sa.column('capacity', sa.Integer()),
    )
    contributions = sa.table(
        'booking_contributions',
        sa.column('booking_id', sa.Integer()),
        sa.column('user_id', sa.Integer()),
        sa.column('contribution_type', sa.String()),
        sa.column('slot_number', sa.Integer()),
        sa.column('amount_due', sa.Numeric(12, 2)),
        sa.column('amount_paid', sa.Numeric(12, 2)),
        sa.column('status', sa.String()),
        sa.column('expires_at', sa.DateTime()),
        sa.column('created_at', sa.DateTime()),
    )
    rows = list(
        bind.execute(
            sa.select(
                bookings.c.id,
                bookings.c.user_id,
                bookings.c.payment_mode,
                bookings.c.total_amount,
                bookings.c.paid_amount,
                bookings.c.status,
                bookings.c.initial_payment_due_at,
                bookings.c.created_at,
                fields.c.capacity,
            ).select_from(
                bookings.join(fields, bookings.c.field_id == fields.c.id)
            )
        ).mappings()
    )

    terminal_statuses = {'CANCELLED', 'EXPIRED', 'REJECTED'}
    for row in rows:
        total = Decimal(row['total_amount'])
        paid_remaining = Decimal(row['paid_amount'])
        planned = []
        if row['payment_mode'] == 'SPLIT_OPPONENT':
            creator_due = Decimal(int(total) // 2)
            planned = [
                ('CREATOR', None, creator_due, row['user_id']),
                ('OPPONENT', 1, total - creator_due, None),
            ]
        elif row['payment_mode'] == 'SPLIT_PLAYERS':
            total_players = max(int(row['capacity'] or 0), 2)
            total_vnd = int(total)
            base_share, remainder = divmod(total_vnd, total_players)
            external_due = Decimal(base_share + remainder)
            external_due += total - Decimal(total_vnd)
            creator_due = total - external_due
            bind.execute(
                bookings.update()
                .where(bookings.c.id == row['id'])
                .values(
                    split_total_players=total_players,
                    split_required_players=1,
                )
            )
            planned = [
                ('CREATOR', None, creator_due, row['user_id']),
                ('PLAYER', 1, external_due, None),
            ]
        else:
            planned = [('CREATOR', None, total, row['user_id'])]

        for contribution_type, slot_number, amount_due, user_id in planned:
            amount_paid = min(paid_remaining, amount_due)
            paid_remaining -= amount_paid
            if amount_paid == amount_due:
                contribution_status = 'PAID'
            elif row['status'] in terminal_statuses:
                contribution_status = 'EXPIRED'
            else:
                contribution_status = 'PENDING'
            bind.execute(
                contributions.insert().values(
                    booking_id=row['id'],
                    user_id=user_id,
                    contribution_type=contribution_type,
                    slot_number=slot_number,
                    amount_due=amount_due,
                    amount_paid=amount_paid,
                    status=contribution_status,
                    expires_at=(
                        row['initial_payment_due_at']
                        if contribution_type == 'CREATOR'
                        else None
                    ),
                    created_at=row['created_at'],
                )
            )
