"""create venues table

Revision ID: 46d144661ea0
Revises: 90b6736cc5ac
Create Date: 2026-08-07 01:03:06.795881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '46d144661ea0'
down_revision = '90b6736cc5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=150), nullable=False),
    sa.Column('address', sa.Unicode(length=255), nullable=False),
    sa.Column('district', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('opening_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('closing_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('moderation_note', sa.Unicode(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'HIDDEN', 'INACTIVE')", name='ck_venues_status'),
    sa.CheckConstraint('opening_time < closing_time', name='ck_venues_opening_before_closing'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index('ix_venues_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index('ix_venues_status_city', ['status', 'city'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index('ix_venues_status_city')
        batch_op.drop_index('ix_venues_owner_created')

    op.drop_table('venues')
    # ### end Alembic commands ###
