"""create matches and match participants

Revision ID: 5bcf59c01c23
Revises: 3f1f38dab5f1
Create Date: 2026-08-10 23:24:16.436997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5bcf59c01c23'
down_revision = '3f1f38dab5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('skill_level', sa.String(length=30), nullable=True),
    sa.Column('total_players', sa.Integer(), nullable=True),
    sa.Column('required_players', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("((match_type = 'FIND_OPPONENT' AND required_players = 1 AND total_players IS NULL) OR (match_type = 'FIND_PLAYERS' AND total_players IS NOT NULL AND total_players > 1 AND required_players < total_players))", name='ck_matches_configuration'),
    sa.CheckConstraint("match_type IN ('FIND_PLAYERS', 'FIND_OPPONENT')", name='ck_matches_type'),
    sa.CheckConstraint("status IN ('OPEN', 'FULL', 'CONFIRMED', 'CANCELLED', 'COMPLETED')", name='ck_matches_status'),
    sa.CheckConstraint('required_players > 0', name='ck_matches_required_players_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_status_created', ['status', 'created_at'], unique=False)

    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Unicode(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('payment_due_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('decided_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("participant_type IN ('PLAYER', 'OPPONENT_REPRESENTATIVE')", name='ck_match_participants_type'),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED_AWAITING_PAYMENT', 'JOINED', 'REJECTED', 'EXPIRED', 'WITHDRAWN')", name='ck_match_participants_status'),
    sa.ForeignKeyConstraint(['contribution_id'], ['booking_contributions.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.create_index('ix_match_participants_match_status', ['match_id', 'status'], unique=False)
        batch_op.create_index('uq_match_participants_active_user', ['match_id', 'user_id'], unique=True, mssql_where=sa.text("status IN ('PENDING', 'ACCEPTED_AWAITING_PAYMENT', 'JOINED')"), sqlite_where=sa.text("status IN ('PENDING', 'ACCEPTED_AWAITING_PAYMENT', 'JOINED')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.drop_index('uq_match_participants_active_user', mssql_where=sa.text("status IN ('PENDING', 'ACCEPTED_AWAITING_PAYMENT', 'JOINED')"), sqlite_where=sa.text("status IN ('PENDING', 'ACCEPTED_AWAITING_PAYMENT', 'JOINED')"))
        batch_op.drop_index('ix_match_participants_match_status')

    op.drop_table('match_participants')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_status_created')

    op.drop_table('matches')
    # ### end Alembic commands ###
