"""create field price slots table

Revision ID: 78fbcd7c9576
Revises: 1991532703dc
Create Date: 2026-08-08 00:13:15.634988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '78fbcd7c9576'
down_revision = '1991532703dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_price_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger().with_variant(mssql.TINYINT(), 'mssql'), nullable=False),
    sa.Column('start_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('end_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('hourly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_price_slots_status'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_price_slots_day_of_week'),
    sa.CheckConstraint('hourly_price > 0', name='ck_price_slots_hourly_price_positive'),
    sa.CheckConstraint('start_time < end_time', name='ck_price_slots_start_before_end'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_price_slots', schema=None) as batch_op:
        batch_op.create_index('ix_price_slots_field_day_status_time', ['field_id', 'day_of_week', 'status', 'start_time', 'end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_price_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_price_slots_field_day_status_time')

    op.drop_table('field_price_slots')
    # ### end Alembic commands ###
