"""create bookings and price snapshots

Revision ID: 8aecda33c702
Revises: 95239df4b6b1
Create Date: 2026-08-08 01:27:04.984892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '8aecda33c702'
down_revision = '95239df4b6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_code', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('end_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('cancellation_fee_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('owner_response_due_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('initial_payment_due_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('funding_deadline', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('note', sa.Unicode(length=500), nullable=True),
    sa.Column('rejection_reason', sa.Unicode(length=500), nullable=True),
    sa.Column('cancellation_reason', sa.Unicode(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("payment_mode IN ('FULL_PAYMENT', 'SPLIT_OPPONENT', 'SPLIT_PLAYERS')", name='ck_bookings_payment_mode'),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'PARTIALLY_PAID', 'PAID', 'REFUND_PENDING', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name='ck_bookings_status'),
    sa.CheckConstraint('cancellation_fee_amount >= 0 AND cancellation_fee_amount <= paid_amount', name='ck_bookings_cancellation_fee_range'),
    sa.CheckConstraint('paid_amount >= 0 AND paid_amount <= total_amount', name='ck_bookings_paid_amount_range'),
    sa.CheckConstraint('start_time < end_time', name='ck_bookings_start_before_end'),
    sa.CheckConstraint('total_amount > 0', name='ck_bookings_total_amount_positive'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_code')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_field_date_status_time', ['field_id', 'booking_date', 'status', 'start_time', 'end_time'], unique=False)
        batch_op.create_index('ix_bookings_status_funding_deadline', ['status', 'funding_deadline'], unique=False)
        batch_op.create_index('ix_bookings_status_owner_due', ['status', 'owner_response_due_at'], unique=False)
        batch_op.create_index('ix_bookings_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('booking_price_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('price_slot_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('end_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('hourly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_booking_price_details_duration_positive'),
    sa.CheckConstraint('hourly_price > 0', name='ck_booking_price_details_hourly_price_positive'),
    sa.CheckConstraint('start_time < end_time', name='ck_booking_price_details_start_before_end'),
    sa.CheckConstraint('subtotal > 0', name='ck_booking_price_details_subtotal_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['price_slot_id'], ['field_price_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_price_details', schema=None) as batch_op:
        batch_op.create_index('ix_booking_price_details_booking_time', ['booking_id', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_price_details', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_price_details_booking_time')

    op.drop_table('booking_price_details')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_user_created')
        batch_op.drop_index('ix_bookings_status_owner_due')
        batch_op.drop_index('ix_bookings_status_funding_deadline')
        batch_op.drop_index('ix_bookings_field_date_status_time')

    op.drop_table('bookings')
    # ### end Alembic commands ###
