"""create owner applications table

Revision ID: 90b6736cc5ac
Revises: 378937fd70e9
Create Date: 2026-08-07 00:24:10.028381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '90b6736cc5ac'
down_revision = '378937fd70e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.Unicode(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Unicode(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Unicode(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')", name='ck_owner_applications_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_applications', schema=None) as batch_op:
        batch_op.create_index('uq_owner_applications_pending_user', ['user_id'], unique=True, mssql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_applications', schema=None) as batch_op:
        batch_op.drop_index('uq_owner_applications_pending_user', mssql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))

    op.drop_table('owner_applications')
    # ### end Alembic commands ###
