"""create field maintenances table

Revision ID: 95239df4b6b1
Revises: 78fbcd7c9576
Create Date: 2026-08-08 00:51:57.863206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '95239df4b6b1'
down_revision = '78fbcd7c9576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_maintenances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('end_time', sa.Time().with_variant(mssql.TIME(precision=0), 'mssql'), nullable=False),
    sa.Column('reason', sa.Unicode(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'CANCELLED', 'COMPLETED')", name='ck_field_maintenances_status'),
    sa.CheckConstraint('start_time < end_time', name='ck_field_maintenances_start_before_end'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_maintenances', schema=None) as batch_op:
        batch_op.create_index('ix_field_maintenances_field_date_status_time', ['field_id', 'maintenance_date', 'status', 'start_time', 'end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_maintenances', schema=None) as batch_op:
        batch_op.drop_index('ix_field_maintenances_field_date_status_time')

    op.drop_table('field_maintenances')
    # ### end Alembic commands ###
